name: termusic
adopt-info: termusic
summary: Terminal Music and Podcast Player written in Rust
description: |
    Listen to music and podcasts freely as both in freedom and free of charge!

license: GPL-3.0

base: core20
grade: stable
confinement: classic
compression: lzo

apps:
  termusic:
    command: usr/bin/snapcraft-preload termusic
    environment:
      PATH: $SNAP/bin/:$PATH
   
parts:
  termusic:
    source: https://github.com/tramhao/termusic
    source-type: git
    plugin: rust
    
    build-packages:
      - libasound2-dev
      - gstreamer1.0-alsa
      - mpv
      - openssl
      - libssl-dev
      - libdbus-1-dev 
      - pkg-config
      - protobuf-compiler
      
    stage-packages:
      - libasound2 
      - gstreamer1.0-alsa
      - mpv 
      - openssl
      - libssl1.1
      - libdbus-1-dev
      - libglu1-mesa
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f2)"
      
    after: 
      - snapcraft-preload
      
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DLIBPATH=/usr/lib
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - lib32stdc++6        
